/* Pdmp object interface */

#ifndef Py_PDMP_H
#define Py_PDMP_H
#ifdef __cplusplus
extern "C" {
#endif

static const char dump_magic[13];

/* This random fingerprint was generated by the shell command:

   shuf -i 0-255 -n 32 -r | awk '{printf "   0x%.02X,\n", $0}'

   In the final Emacs executable, this random fingerprint is replaced
   by a fingerprint of the temporary Emacs executable that was built
   along the way.  */

static const unsigned char fingerprint[32];

struct dump_location {
  /* Index into the dump table entries. */
  size_t index;
};

struct dump_header {
  /* File type magic.  */
  char magic[sizeof dump_magic];

  unsigned char fingerprint[sizeof fingerprint];

  struct dump_location entry_point;
};

struct dump_reloc_entry {
  size_t base_offset;
  size_t extent;
};

typedef struct {
  PyObject_HEAD

  Py_ssize_t mapped_memory_length;
  Py_ssize_t fd;
  void* mapped_memory_region;

  struct dump_header *header;
  size_t *num_entries;
  struct dump_reloc_entry *entries;
  void* data;
} pdmp;

struct dump_context {
  /* Header we'll write to the dump file when done.  */
  struct dump_header header;

  /* The object to dump. */
  PyObject* source_object;

  /* File descriptor for dump file; < 0 if closed.  */
  int fd;
  /* Name of dump file --- used for error reporting.  */
  PyObject* dump_filename;

  /* Queue of objects to dump.  */
  /* PyObject* dump_queue; */
};

PyAPI_DATA(PyTypeObject) Pdmp_Type;

#ifdef __cplusplus
}
#endif
#endif /* !Py_PDMP_H */
